### PR TITLE
fix retrieving enrollment trigger

### LINKED ISSUE #219: Wrong enrollment trigger retrieved when to a (user_id, post_id) tuple corresponds more than one trigger
### Reproduction Steps

+ Enroll a student to a course manually (will generate an enrollment trigger like **admin_{admin_id}**)
+ Unenroll the student
+ Now enroll the student with a different trigger, e.g. a different admin, or if the course is an "auto-enroll" corse of a membership, enroll the student to the membership, so that the new trigger will be like **membership_{membership_id}**
+ Retrieve the enrollment via rest-api

### Expected Behavior

+ I would expect that the retrieved enrollment's trigger reads **membership_{membership_id}** (the latest enrollment trigger)

### Actual Behavior

+ The retrieved enrollment's trigger reads **admin_{admin_id}** (the first enrollment trigger)

### Error Messages / Logs

```
n/a

```

### System Information

LifterLMS 4.11.0
LifterLMS Rest Api v1.0.0-beta.17

### Browser, Device, and Operating System Information

n/a

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #219

## How has this been tested?
Manually and with new unit test which was developed and ran before fixing the issue.

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: tests/unit-tests/server/class-llms-rest-test-enrollments.php [hunk 1]
```diff
@@ -440,18 +442,18 @@ public function test_update_enrollment_status() {
...
 		$student->enroll( $course_id, 'whatever_trigger' );
-		// unenroll.
+		// Unenroll.
 		$student->unenroll( $course_id );
 		$this->assertEquals( 'expired', $student->get_enrollment_status( $course_id ) );
 		$this->assertEquals( 'whatever_trigger', $student->get_enrollment_trigger( $course_id, false ) );
 
-		// enroll via api.
-		sleep(1); //<- to be sure the new status is subsequent the one previously set.
+		// Wnroll via api.
```
Comment (thomasplevy) [inline tests/unit-tests/server/class-llms-rest-test-enrollments.php]:
```suggestion
		// Enroll via api.
```

**Review by thomasplevy — APPROVED** [review]
