### PR TITLE
Fixed access plan `availability_restrictions` property never returned

### LINKED ISSUE #269: access plan `availability_restrictions` property never returned
### Reproduction Steps

+ Create an access plan with membership restrictions stored in the `availability_restrictions` property.
+ Retrieve the access plan via a `GET /access-plans/$id` request or a `GET /access-plans` (list) request that would return the access plan with restrictions

### Expected Behavior

+ The `availability_restrictions` property contains an array of WP_Post IDs

### Actual Behavior

+ An empty array is returned.

---

Looks like the error is here:

https://github.com/gocodebox/lifterlms-rest/blob/a3a644da3edd10d923e967fe0b6244606d3d1f5f/includes/server/class-llms-rest-access-plans-controller.php#L278

the empty array is in the wrong position on the ternary 

Also after the above is corrected, ideally an array of ints should be returned instead of an array of strings

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
Fixes #269 

## How has this been tested?
new unit tests

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

File: tests/unit-tests/server/class-llms-rest-test-access-plans.php [hunk 1]
```diff
@@ -690,13 +691,151 @@ public function test_create_paid_access_plan() {
 		);
 		$this->assertTrue(
 			llms_parse_bool(
-				( new LLMS_Access_Plan( $response->get_data()['id'] ) )->get ('trial_offer' )
+				( new LLMS_Access_Plan( $response->get_data()['id'] ) )->get('trial_offer' )
```
Comment (thomasplevy) [inline tests/unit-tests/server/class-llms-rest-test-access-plans.php]:
```suggestion
				( new LLMS_Access_Plan( $response->get_data()['id'] ) )->get( 'trial_offer' )
```

File: .changelogs/issue_269.yml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+significance: patch
+type: fixed
+links:
+  - "#269"
+entry: Fixed access plan `availability_restrictions` property never returned.
```
Comment (thomasplevy) [inline .changelogs/issue_269.yml]:
```suggestion
entry: Fixed issue causing the access plan `availability_restrictions` property to always return an empty array.
```

**Review by thomasplevy — DISMISSED** [review]

File: tests/unit-tests/server/class-llms-rest-test-access-plans.php (hunk 1 above)
Comment (eri-trabiccolo) [reply tests/unit-tests/server/class-llms-rest-test-access-plans.php]: AH!

**Review by thomasplevy — APPROVED** [review]
